# Generated by Django 5.2.1 on 2025-07-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("RECRUITER", "Recruiter"),
                    ("CANDIDATE", "Candidate"),
                    ("NOT_SET", "Not Set"),
                ],
                default="NOT_SET",
                max_length=20,
            ),
        ),
    ]
