# Generated by Django 5.2.1 on 2025-07-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("RECRUITER", "Recruiter"),
                    ("CANDIDATE", "Candidate"),
                    ("NOT_SET", "Not Set"),
                ],
                default="CANDIDATE",
                max_length=20,
            ),
        ),
    ]
