# Generated by Django 5.2.1 on 2025-07-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("is_recruiter", "can create, update, delete jobs ")]
            },
        ),
    ]
