# Generated by Django 5.2.1 on 2025-07-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("is_recruiter", "Can create,update, delete jobs")]
            },
        ),
    ]
