# Generated by Django 5.2.1 on 2025-07-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
    ]
