# Generated by Django 5.2.1 on 2025-07-17 03:50

import dirtyfields.dirtyfields
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this model instance.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when the instance was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp indicating when the instance was last updated.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DELETED", "Deleted"),
                            ("DRAFT", "Draft"),
                            ("REMOVED", "Removed"),
                        ],
                        default="ACTIVE",
                        help_text="Status of the instance, typically used for soft deletion.",
                        max_length=20,
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deadline", models.DateField()),
            ],
            options={"abstract": False,},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skills",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("PYTHON", "Python"),
                            ("DJANGO", "Django"),
                            ("REACT", "React"),
                            ("NODE", "Node.js"),
                            ("SQL", "SQL"),
                            ("AWS", "AWS"),
                            ("DOCKER", "Docker"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                            ("NOT_SET", "Not Set"),
                        ],
                        default="NOT_SET",
                        max_length=20,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="job.job",
                    ),
                ),
            ],
            options={"unique_together": {("candidate", "job")},},
        ),
    ]
